#+TITLE: Import Textmate bundles into Emacs using lisp
#+AUTHOR: Matthew L. Fidler
* Library Information
 *textmate-to-yas.el* --- Import Textmate macros into yasnippet syntax

 - Filename :: [[file:textmate-to-yas.el][textmate-to-yas.el]]
 - Description :: Import Textmate macros into yasnippet syntax
 - Author :: Matthew L. Fidler
 - Maintainer :: Matthew L. Fidler
 - Created :: Wed Oct 20 15:08:50 2010 (-0500)
 - Version :: 0.15
 - Last-Updated :: Fri Jun 29 12:22:42 2012 (-0500)
 -           By :: Matthew L. Fidler
 -     Update # :: 1747
 - URL :: https://github.com/mlf176f2/textmate-to-yas.el/
 - Keywords :: Yasnippet Textmate
 - Compatibility :: Tested with Windows Emacs 23.2


This library allows you to import TextMate bundle snippets to
Yasnippet

To use, put in a directory in the load path, like ~/elisp and put
the following in ~/.emacs

#+BEGIN_SRC emacs-lisp :results silent
(require 'textmate-to-yas)
#+END_SRC

If you wish to use a snippet from GitHub, just drag the .tar.gz
file to emacs while Yasnippet is running

Notes about importing:
 - Importing depends on what emacs knows about your system.  If a =.R=
   file is opened in =ess-mode=, then it is imported to =ess-mode= snippets.
   Similarly if an =.Rd= file is associated to =Rd-mode=, then it is
   imported to =Rd-mode=.  Hence bundles like
   https://github.com/swissr/rmate.tmbundle will import to two
   different snippet directories.

 - The translations depend on implementing Textmate regular
   expressions in emacs.  Therefore, =textmate-to-yas= needs to be sourced for
   translated snippets since it implements condition insertions syntax
   of Textmated based on a emacs regular expression. (See
   http://manual.macromates.com/en/regular_expressions#conditional_insertions.html)

 - Textmate regular expressions has features that emacs regular
   expressions do not have, for example:

   - look-ahead
   - negative look-ahead
   - look-behind
   - negative look-behind

   These regular expressions are not supported in emacs and cannot be
   translated to yasnippet programatically.  Currently they will be
   ignored.  You may wish to implement  an elisp solution yourself.

 - Binary plists are partially supported with command line tools:
   - Under a mac =plutil= is used to convert binary to xml formats.
   - Under other operating systems =plutil.pl= is used to convert
     binary to xml formats.  Therefore this requires perl to be
     installed for binary conversion.
* Importing A Textmate bundle from the Textmate SVN url
This is done with the command =textmate-import-svn-from-url=.
* Importing from an unzipped Textmate tmBundle
This is done with the command =textmate-import-bundle=.  You need to
specify both the root directory of the bundle ant the parent modes for
importing (like text-mode).
* Functions
** Interactive Functions

** Internal Functions
* Variables
** Customizable Variables

*** textmate-default-key-prefix
When importing key codes, this prefix is used as well.

For example if a Textmate snippet specifies a key of Meta-A, the emacs key specified is
=textmate-default-key-prefix= added to the detected key.  With the default C-c C-y, this
becomes:

C-c C-y M-a

*** textmate-import-convert-known-expressions
Known Textmate Expressions

*** textmate-import-key-bindings
Import key bindings into the snippets.

*** textmate-import-plutil.pl
plutil.pl path to deal with binary plists.

*** textmate-key-to-emacs-key-known
Textmate Key to Emacs Key

*** textmate-regexp-emacs-unsupported
Emacs Unsupported Regular Expression

*** textmate-regexp-to-emacs-regexp-known
Known Textmate to Emacs regular expression translations.

*** textmate-use-define-menu
 - Use =yas/define-menu= or =yas-define-menu= (0.8+) instead of placing the menu choice in the group tag.

** Internal Variables

*** textmate-import-convert-env-lst
List to convert Textmate Environmental variables to customizable fields.

*** textmate-import-saved-guesses
Saved guesses for textmate import

*** textmate-import-svn-pkgs-cache
 - Cached list of Textmate svn bundles

*** textmate-import-svn-url
 - Url for Textmate svn

*** textmate-to-yas-backward-compatability
Yasnippet backward compatability functions used in textmate-to-yas.el

Value: ((yas/expand-snippet yas-expand-snippet)
 (yas/active-field-overlay yas--active-field-overlay)
 (yas/wrap-around-region yas-wrap-around-region)
 (yas/moving-away-p yas-moving-away-p)
 (yas/expand yas-expand)
 (yas/modified-p yas-modified-p)
 (yas/moving-away-p yas-moving-away-p)
 (yas/text yas-text)
 (yas/skip-and-clear-or-delete-char yas-skip-and-clear-or-delete-char)
 (yas/snippet-fields yas--snippet-fields)
 (yas/snippets-at-point yas--snippets-at-point)
 (yas/update-mirrors yas--update-mirrors)
 (yas/fallback-behavior yas-fallback-behavior)
 (yas/minor-mode yas-minor-mode)
 (yas/field-probably-deleted-p yas--field-probably-deleted-p)
 (yas/field yas-field)
 (yas/field-text-for-display yas--field-text-for-display)
 (yas/snippet-control-overlay yas--snippet-control-overlay)
 (yas/exit-snippet yas-exit-snippet)
 (yas/check-commit-snippet yas--check-commit-snippet)
 (yas/define-snippets yas--check-commit-snippet)
 (yas/after-exit-snippet-hook yas-after-exit-snippet-hook))



*** textmate-yas-known-uuid
Known UUIDs for current import.

*** yas---t-lst
Variable for expanding textmate transformations with Yasnippet
* History

 - 12-Sep-2012 ::  First attempt to support 0.8x. Currently untested. ()
 - 29-Jun-2012 ::  Should convert binary plists with either perl and plutil.pl or Mac OSX and plutil (Matthew L. Fidler)
 - 29-Jun-2012 ::  Will not import Textmate snippets that cannot be translated to emacs regular expressions. (Matthew L. Fidler)
 - 29-Jun-2012 ::  Added yas/define-menu support. Should fix issue #2 (Matthew L. Fidler)
 - 27-Jun-2012 ::  @capitaomorte suggested more customization. Implemented. (Matthew L. Fidler)
 - 27-Jun-2012 ::  Added the ability to transform bundle specific transformations (Matthew L. Fidler)
 - 22-Nov-2011 ::  Another small fix for quoted parenthesis \} (Matthew L. Fidler)
 - 22-Nov-2011 ::  Added a fix for Textmate imports to avoid yasnippet bug. See: https://github.com/capitaomorte/yasnippet/issues/197 (Matthew L. Fidler)
 - 21-Nov-2011 ::  Tested with bsd-tar on windows and changed some extraction behaviors. (Matthew L. Fidler)
 - 01-Apr-2011 ::  Changed =yas/ma= so that it applies the mirrors upon moving away. (Matthew L. Fidler)
 - 31-Mar-2011 ::  Add =yas/editing-field-num-p= (Matthew L. Fidler)
 - 08-Feb-2011 ::  Added autoload cookies. (Matthew L. Fidler)
 - 28-Nov-2010 ::  Bug-fix for names. (Matthew L. Fidler)
 - 28-Nov-2010 ::  bug fix for yas/t/ when $1 doesn't exist. (Matthew L. Fidler)
 - 12-Nov-2010 ::  Added #bindings back. (Matthew L. Fidler)
 - 10-Nov-2010 ::  Bug fix to Textmate to Emacs regular expression matching. (Matthew L. Fidler)
 - 09-Nov-2010 ::  Added error fix for TextMate formats (upper and lower case when match isn't found.) (Matthew L. Fidler)
 - 09-Nov-2010 ::  Bug fix for complicated yas/t/ snippets not converting the \ character to \\. (Matthew L. Fidler)
 - 09-Nov-2010 ::  yas/t/ bugfix for missing text. (Matthew L. Fidler)
 - 09-Nov-2010 ::  Added error handler when guessing modes. (Matthew L. Fidler)
 - 09-Nov-2010 ::  Added drag and drop support for Github tar.gz files. Requires Yasnippet to be running. (Matthew L. Fidler)
 - 06-Nov-2010 ::  Changed name. (Matthew L. Fidler)
 - 06-Nov-2010 ::  Handle nested conditional replacements. For example (?3:one:(?2:two:none)) (Matthew L. Fidler)
 - 05-Nov-2010 ::  Textmate import file handles errors gracefully. (Matthew L. Fidler)
 - 05-Nov-2010 ::  Added better textmate support by providing translations for mirrors. Requires the directive # type: command available in the SVN version of yasnippet.  (Matthew L. Fidler)
 05-Nov-2010
   Last-Updated: Fri Nov  5 09:59:30 2010 (-0500) #898 (US041375)
   Changed textmate-replace-in-string with replace-regexp-in-string
04-Nov-2010
   Last-Updated: Thu Nov  4 12:38:32 2010 (-0500) #535 (us041375)
   Changed extension from .yasnippet to what the package is in a svn-import.
04-Nov-2010
   Last-Updated: Thu Nov  4 10:55:27 2010 (-0500) #525 (us041375)
   replace-in-string changed to textmate-replace-in-string.  May be missing on some systems.
 - 01-Nov-2010 ::  Bug fix for expand-env (Matthew L. Fidler)
 - 01-Nov-2010 ::  Added more supported tags. (Matthew L. Fidler)
 - 01-Nov-2010 ::  Took out #scope pseudo-directive. (Matthew L. Fidler)
 - 01-Nov-2010 ::  Added more file extensions. (Matthew L. Fidler)
 - 28-Oct-2010 ::  Removed bindings. They are currently causing problems... (Matthew L. Fidler)
 - 28-Oct-2010 ::  Added completed import of svn bundle message. (Matthew L. Fidler)
 - 28-Oct-2010 ::  Bug fix to allow files to be .yasnippet instead of _yasnippet files. (Matthew L. Fidler)
 - 27-Oct-2010 ::  Added fix to allow files to pass for directories in =textmate-import-bundle= (Matthew L. Fidler)
 - 27-Oct-2010 ::  Added import from svn.textmate.org using url package. Use =textmate-import-svn-url= (Matthew L. Fidler)
 - 27-Oct-2010 ::  Added a guess-mode function to take out prompting for modes. (Matthew L. Fidler)
 - 25-Oct-2010 ::  Bug fix for .yas-parents. (Matthew L. Fidler)
 - 25-Oct-2010 ::  Changed import rmate and stata to mirror new textmate-import function (Matthew L. Fidler)
 - 25-Oct-2010 ::  Changed parent-mode to a prompt and uses .yas-parents as in SVN trunk of yasnippet. (Matthew L. Fidler)
 - 22-Oct-2010 ::  Bugfix for ${1:default} expressions (Matthew L. Fidler)
 - 22-Oct-2010 ::  Added ability to choose mode by function or mode-name (Matthew L. Fidler)
 - 21-Oct-2010 ::  Selected text bugfix (Matthew L. Fidler)
 - 21-Oct-2010 ::  Now handles key-bindings as well. (Matthew L. Fidler)
 - 21-Oct-2010 ::  Added a fix to take out spaces in textmate bundles file name translations. (Matthew L. Fidler)
 - 21-Oct-2010 ::  Updated import to find groupings before or after orderings in the info.plist.  (Matthew L. Fidler)
 - 21-Oct-2010 ::  Added a yas/root-directory of the current directory if undefined. Allows to be run from the command line by just loading this file  (Matthew L. Fidler)
 - 21-Oct-2010 :: 20-Oct-2010 Matthew L. Fidler Bug fix -- added mode.  (Matthew L. Fidler)
