#+TITLE: Import Textmate bundles into Emacs using lisp
#+AUTHOR: Matthew L. Fidler
* Library Information
 /textmate-to-yas.el/ --- Import Textmate macros into yasnippet syntax

 - Filename :: [[file:textmate-to-yas.el][textmate-to-yas.el]]
 - Description :: Import Textmate macros into yasnippet syntax
 - Author :: Matthew L. Fidler
 - Maintainer :: Matthew L. Fidler
 - Created :: Wed Oct 20 15:08:50 2010 (-0500)
 - Version :: 0.17
 - Last-Updated :: Fri Jun 29 12:22:42 2012 (-0500)
 -           By :: Matthew L. Fidler
 -     Update # :: 1747
 - URL :: https://github.com/mlf176f2/textmate-to-yas.el/
 - Keywords :: Yasnippet Textmate
 - Compatibility :: Tested with Windows Emacs 23.2

* Importing A Textmate bundle from the Textmate SVN url
This is done with the command =textmate-import-svn-from-url=.
* Importing from an unzipped Textmate tmBundle
This is done with the command =textmate-import-bundle=.  You need to
specify both the root directory of the bundle ant the parent modes for
importing (like text-mode).
* Functions
** Interactive Functions

*** textmate-import-bundle
=(textmate-import-bundle DIR PARENT-MODES &optional ORIGINAL-AUTHOR
YAS-DIR MODE TRANSFORM-FUNCTION)=

Imports textmate bundle to new-dir.  Mode may be a string or a function determining which mode to place files in...

*** textmate-import-git-tar.gz
=(textmate-import-git-tar\.gz FILE PARENT-MODES)=

 - Imports a TextMate git-hub bundle.

*** textmate-import-svn-from-url
=(textmate-import-svn-from-url)=

 - Imports a textmate bundle and extracts snippets from =textmate-import-svn-url=

*** yas-editing-field-num-p
=(yas-editing-field-num-p &optional ARG)=

Which field is active?

** Internal Functions

*** textmate-get-group
=(textmate-get-group UUID PLIST)=

 - Gets group from textmate info.plist file

*** textmate-import-add-to-alist
=(textmate-import-add-to-alist ALIST-VAR ELT-CONS &optional NO-REPLACE)=

Add to the value of ALIST-VAR an element ELT-CONS if it isn't there yet.
If an element with the same car as the car of ELT-CONS is already present,
replace it with ELT-CONS unless NO-REPLACE is non-nil; if a matching
element is not already present, add ELT-CONS to the front of the alist.
The test for presence of the car of ELT-CONS is done with =equal=.

*** textmate-import-convert-template
=(textmate-import-convert-template TEMPLATE)=

 - Converts template to Yasnippet template

*** textmate-import-convert-template-t
=(textmate-import-convert-template-t BEGIN-TEXT MAX)=

 - Subroutine to convert regular expressions to (yas---t expressions)

*** textmate-import-convert-to-xml
=(textmate-import-convert-to-xml FILE)=

Converts a binary plist to XML

*** textmate-import-current-buffer
=(textmate-import-current-buffer NEW-DIR &optional PLIST BUFFER-NAME
ORIGINAL-AUTHOR MODE-STRING-OR-FUNCTION TRANSFORM-FUNCTION
PARENT-MODES EXT)=

 - Changes Textmate (current buffer) plist to yas snippet.

*** textmate-import-drag-and-drop
=(textmate-import-drag-and-drop URI &rest IGNORE)=

 - Drag and drop interface to import files.

*** textmate-import-file
=(textmate-import-file FILE NEW-DIR &optional MODE ORIGINAL-AUTHOR
PLIST TRANSFORM-FUNCTION PARENT-MODES)=

 - Imports textmate file

*** textmate-import-get-property
=(textmate-import-get-property NAME START STOP)=

 - Get property from plist

*** textmate-import-guess-mode
=(textmate-import-guess-mode SCOPE-O &optional SNIPPET-Q)=

 - Guesses mode based on Textmate scope.

*** textmate-import-guess-possiblities
=(textmate-import-guess-possiblities P-QUOTE MATCH-STRING)=

 - Guesses possible modes...

*** textmate-import-rmate
=(textmate-import-rmate DIR &optional NEW-DIR)=

 - Example Function for importing Rmate into Yasnippet

*** textmate-import-snippets-supported
=(textmate-import-snippets-supported TEXTMATE-URL)=

Check to see if snippets are supported

*** textmate-import-stata
=(textmate-import-stata DIR &optional NEW-DIR)=

*Example function for importing Sata snippets into Yasnippet

*** textmate-import-svn-get-pkgs
=(textmate-import-svn-get-pkgs)=

 - Gets textmate bundles from svn

*** textmate-import-svn-snippets
=(textmate-import-svn-snippets SNIPPET-URL PLIST TEXTMATE-NAME)=

*Imports snippets based on textmate svn tree.

*** textmate-regexp-to-emacs-regexp
=(textmate-regexp-to-emacs-regexp REXP)=

 - Convert a textmate regular expression to an emacs regular expression (as much as possible)

*** textmate-yas-menu
=(textmate-yas-menu PLIST &optional MODE-NAME)=

 - Builds =yas-define-menu=from info.plist file

*** textmate-yas-menu-get-items
=(textmate-yas-menu-get-items TXT)=

Gets items from TXT and puts them into a list

*** yas---t/
=(yas---t/ TEXTMATE-REG TEXTMATE-REP &optional TEXTMATE-OPTION T-TEXT)=

 - Textmate like mirror.  Uses textmate regular expression and textmate formatting.

*** yas-format-match-?-buf
=(yas-format-match-\?-buf TEXT &optional STRING EMPTY-MISSING
START-POINT STOP-POINT)=

 - Recursive call to temporary buffer to replace conditional formats.

*** yas-getenv
=(yas-getenv VAR)=

 - Gets environment variable or customized variable for Textmate->Yasnippet conversion

*** yas-replace-match
=(yas-replace-match TEXT &optional STRING
TREAT-EMPTY-MATCHES-AS-MISSING-MATCHES SUBEXP)=

 - yas-replace-match is similar to emacs replace-match but using Textmate formats

*** yas-text-on-moving-away
=(yas-text-on-moving-away DEFAULT-TEXT)=

 - Changes text when moving away AND original text has not changed
* Variables
** Customizable Variables

*** textmate-default-key-prefix
When importing key codes, this prefix is used as well.

For example if a Textmate snippet specifies a key of Meta-A, the emacs key specified is
=textmate-default-key-prefix= added to the detected key.  With the default C-c C-y, this
becomes:

C-c C-y M-a

*** textmate-import-convert-known-expressions
Known Textmate Expressions

*** textmate-import-key-bindings
Import key bindings into the snippets.

*** textmate-import-plutil.pl
plutil.pl path to deal with binary plists.

*** textmate-key-to-emacs-key-known
Textmate Key to Emacs Key

*** textmate-regexp-emacs-unsupported
Emacs Unsupported Regular Expression

*** textmate-regexp-to-emacs-regexp-known
Known Textmate to Emacs regular expression translations.

*** textmate-use-define-menu
 - Use =yas/define-menu= or =yas-define-menu= (0.8+) instead of placing the menu choice in the group tag.

** Internal Variables

*** textmate-import-backward
textmate-import use backward compatability?

*** textmate-import-convert-env-lst
List to convert Textmate Environmental variables to customizable fields.

*** textmate-import-saved-guesses
Saved guesses for textmate import

*** textmate-import-svn-pkgs-cache
 - Cached list of Textmate svn bundles

*** textmate-import-svn-url
 - Url for Textmate svn

*** textmate-to-yas-backward-compatability
Yasnippet backward compatability functions used in textmate-to-yas.el

Value: ((yas/expand-snippet yas-expand-snippet)
 (yas/active-field-overlay yas--active-field-overlay)
 (yas/wrap-around-region yas-wrap-around-region)
 (yas/moving-away-p yas-moving-away-p)
 (yas/expand yas-expand)
 (yas/modified-p yas-modified-p)
 (yas/moving-away-p yas-moving-away-p)
 (yas/text yas-text)
 (yas/skip-and-clear-or-delete-char yas-skip-and-clear-or-delete-char)
 (yas/snippet-fields yas--snippet-fields)
 (yas/snippets-at-point yas--snippets-at-point)
 (yas/update-mirrors yas--update-mirrors)
 (yas/fallback-behavior yas-fallback-behavior)
 (yas/minor-mode yas-minor-mode)
 (yas/field-probably-deleted-p yas--field-probably-deleted-p)
 (yas/field yas-field)
 (yas/field-text-for-display yas--field-text-for-display)
 (yas/snippet-control-overlay yas--snippet-control-overlay)
 (yas/exit-snippet yas-exit-snippet)
 (yas/check-commit-snippet yas--check-commit-snippet)
 (yas/define-snippets yas--check-commit-snippet)
 (yas/after-exit-snippet-hook yas-after-exit-snippet-hook))



*** textmate-yas-known-uuid
Known UUIDs for current import.

*** yas---t-lst
Variable for expanding textmate transformations with Yasnippet
* History

 - 18-Oct-2012 ::  Bug fix for yasnippet backward compatibility. (Matthew L. Fidler)
 - 18-Sep-2012 ::  Backward compatibility update. (Matthew L. Fidler)
 - 12-Sep-2012 ::  First attempt to support 0.8x. Currently untested. (Matthew L. Fidler)
 - 29-Jun-2012 ::  Should convert binary plists with either perl and plutil.pl or Mac OSX and plutil (Matthew L. Fidler)
 - 29-Jun-2012 ::  Will not import Textmate snippets that cannot be translated to emacs regular expressions. (Matthew L. Fidler)
 - 29-Jun-2012 ::  Added yas/define-menu support. Should fix issue #2 (Matthew L. Fidler)
 - 27-Jun-2012 ::  @capitaomorte suggested more customization. Implemented. (Matthew L. Fidler)
 - 27-Jun-2012 ::  Added the ability to transform bundle specific transformations (Matthew L. Fidler)
 - 22-Nov-2011 ::  Another small fix for quoted parenthesis \} (Matthew L. Fidler)
 - 22-Nov-2011 ::  Added a fix for Textmate imports to avoid yasnippet bug. See: https://github.com/capitaomorte/yasnippet/issues/197 (Matthew L. Fidler)
 - 21-Nov-2011 ::  Tested with bsd-tar on windows and changed some extraction behaviors. (Matthew L. Fidler)
 - 01-Apr-2011 ::  Changed =yas/ma= so that it applies the mirrors upon moving away. (Matthew L. Fidler)
 - 31-Mar-2011 ::  Add =yas/editing-field-num-p= (Matthew L. Fidler)
 - 08-Feb-2011 ::  Added autoload cookies. (Matthew L. Fidler)
 - 28-Nov-2010 ::  Bug-fix for names. (Matthew L. Fidler)
 - 28-Nov-2010 ::  bug fix for yas/t/ when $1 doesn't exist. (Matthew L. Fidler)
 - 12-Nov-2010 ::  Added #bindings back. (Matthew L. Fidler)
 - 10-Nov-2010 ::  Bug fix to Textmate to Emacs regular expression matching. (Matthew L. Fidler)
 - 09-Nov-2010 ::  Added error fix for TextMate formats (upper and lower case when match isn't found.) (Matthew L. Fidler)
 - 09-Nov-2010 ::  Bug fix for complicated yas/t/ snippets not converting the \ character to \\. (Matthew L. Fidler)
 - 09-Nov-2010 ::  yas/t/ bugfix for missing text. (Matthew L. Fidler)
 - 09-Nov-2010 ::  Added error handler when guessing modes. (Matthew L. Fidler)
 - 09-Nov-2010 ::  Added drag and drop support for Github tar.gz files. Requires Yasnippet to be running. (Matthew L. Fidler)
 - 06-Nov-2010 ::  Changed name. (Matthew L. Fidler)
 - 06-Nov-2010 ::  Handle nested conditional replacements. For example (?3:one:(?2:two:none)) (Matthew L. Fidler)
 - 05-Nov-2010 ::  Textmate import file handles errors gracefully. (Matthew L. Fidler)
 - 05-Nov-2010 ::  Added better textmate support by providing translations for mirrors. Requires the directive # type: command available in the SVN version of yasnippet.  (Matthew L. Fidler)
 - 05-Nov-2010 ::  Changed textmate-replace-in-string with replace-regexp-in-string (US041375)
 - 04-Nov-2010 ::  Changed extension from .yasnippet to what the package is in a svn-import. (us041375)
 - 04-Nov-2010 ::  replace-in-string changed to textmate-replace-in-string. May be missing on some systems. (us041375)
 - 01-Nov-2010 ::  Bug fix for expand-env (Matthew L. Fidler)
 - 01-Nov-2010 ::  Added more supported tags. (Matthew L. Fidler)
 - 01-Nov-2010 ::  Took out #scope pseudo-directive. (Matthew L. Fidler)
 - 01-Nov-2010 ::  Added more file extensions. (Matthew L. Fidler)
 - 28-Oct-2010 ::  Removed bindings. They are currently causing problems... (Matthew L. Fidler)
 - 28-Oct-2010 ::  Added completed import of svn bundle message. (Matthew L. Fidler)
 - 28-Oct-2010 ::  Bug fix to allow files to be .yasnippet instead of _yasnippet files. (Matthew L. Fidler)
 - 27-Oct-2010 ::  Added fix to allow files to pass for directories in =textmate-import-bundle= (Matthew L. Fidler)
 - 27-Oct-2010 ::  Added import from svn.textmate.org using url package. Use =textmate-import-svn-url= (Matthew L. Fidler)
 - 27-Oct-2010 ::  Added a guess-mode function to take out prompting for modes. (Matthew L. Fidler)
 - 25-Oct-2010 ::  Bug fix for .yas-parents. (Matthew L. Fidler)
 - 25-Oct-2010 ::  Changed import rmate and stata to mirror new textmate-import function (Matthew L. Fidler)
 - 25-Oct-2010 ::  Changed parent-mode to a prompt and uses .yas-parents as in SVN trunk of yasnippet. (Matthew L. Fidler)
 - 22-Oct-2010 ::  Bugfix for ${1:default} expressions (Matthew L. Fidler)
 - 22-Oct-2010 ::  Added ability to choose mode by function or mode-name (Matthew L. Fidler)
 - 21-Oct-2010 ::  Selected text bugfix (Matthew L. Fidler)
 - 21-Oct-2010 ::  Now handles key-bindings as well. (Matthew L. Fidler)
 - 21-Oct-2010 ::  Added a fix to take out spaces in textmate bundles file name translations. (Matthew L. Fidler)
 - 21-Oct-2010 ::  Updated import to find groupings before or after orderings in the info.plist.  (Matthew L. Fidler)
 - 21-Oct-2010 ::  Added a yas/root-directory of the current directory if undefined. Allows to be run from the command line by just loading this file  (Matthew L. Fidler)
 - 21-Oct-2010 :: 20-Oct-2010 Matthew L. Fidler Bug fix -- added mode.  (Matthew L. Fidler)
